# Generated by Django 5.1.3 on 2024-11-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('vin', models.CharField(db_column='VIN', max_length=17, primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Cars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('make', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('numberofcylinders', models.IntegerField(blank=True, db_column='numberOfCylinders', null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('drivewheel', models.CharField(blank=True, db_column='driveWheel', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.IntegerField(db_column='employeeID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('locationid', models.IntegerField(db_column='locationID', primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewid', models.IntegerField(db_column='reviewID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warranties',
            fields=[
                ('warrantyid', models.IntegerField(db_column='warrantyID', primary_key=True, serialize=False)),
                ('startdate', models.DateField(db_column='startDate')),
                ('enddate', models.DateField(db_column='endDate')),
                ('coveragedetail', models.CharField(blank=True, db_column='coverageDetail', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Warranties',
                'managed': False,
            },
        ),
    ]
